DROP TABLE IF EXISTS CURRENCY;
DROP TABLE IF EXISTS CONVERSION;

CREATE TABLE CURRENCY(
    currency VARCHAR(3) UNIQUE
);

CREATE TABLE CONVERSION (
  id INT AUTO_INCREMENT PRIMARY KEY,
  base_currency VARCHAR(3) NOT NULL,
  target_currency VARCHAR(3) NOT NULL,
  base_amount DECIMAL(19, 4) NOT NULL,
  target_amount DECIMAL(19, 4) NOT NULL,
  exchange_rate FLOAT NOT NULL,
  transaction_id UUID DEFAULT RANDOM_UUID() NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (base_currency) REFERENCES CURRENCY (currency),
  FOREIGN KEY (target_currency) REFERENCES CURRENCY (currency)
);